### PR TITLE
Seed clinician messages

### PR DESCRIPTION
**Pull request by arkadiuszbachorski**
# Seed clinician messages

## :recycle: Current situation & Problem
As a part of dev process, it's great to see all possible messages. This is very minimal implementation of clinician messages seed.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by pauljohanneskraft — APPROVED** [review]
This is fine for now, but I would actually prefer an implementation where only the assigned clinician gets the messages of the patient, so that it reflects actual behavior - we can either implement it here in that form (e.g. by also defining assigned clinicians in the seeding data already) - or we postpone it in a separate issue - you decide 😊

**Comment by arkadiuszbachorski** [comment]
> This is fine for now, but I would actually prefer an implementation where only the assigned clinician gets the messages of the patient, so that it reflects actual behavior - we can either implement it here in that form (e.g. by also defining assigned clinicians in the seeding data already) - or we postpone it in a separate issue - you decide 😊

Agree, it would be great for this to reflect actual app behavior as close as possible. I am on it, let's not merge it yet!

**Comment by pauljohanneskraft** [comment]
> Agree, it would be great for this to reflect actual app behavior as close as possible. I am on it, let's not merge it yet!

Thank you very much!

**Comment by arkadiuszbachorski** [comment]
@pauljohanneskraft [Add clinician-patient relationship to seeding](https://github.com/StanfordBDHG/ENGAGE-HF-Firebase/pull/142/commits/576f2e14e3653d00828bd5424b69bfbebbcd0c10)

Now, clinician receives notifications for his own patients only. Some clinicians have multiple patients, some have just one, I've added some "chaos" there.

**Comment by pauljohanneskraft** [comment]
Thank you very much for these changes - There is also a way to just seed certain users and currently that one just calls `_seedPatientCollections` - do you have an idea, how we could incorporate that as well? We could just fetch the user right before calling the function and checking its type for example?

**Review by pauljohanneskraft — APPROVED** [review]
Minor remark about possibly adapting this one case, where we would just seed any user with patient data when specifically seeding certain userIds. It may be out of scope of this PR though, so feel free to also merge directly, if preferred.

**Comment by arkadiuszbachorski** [comment]
> Minor remark about possibly adapting this one case, where we would just seed any user with patient data when specifically seeding certain userIds. It may be out of scope of this PR though, so feel free to also merge directly, if preferred.


I created a separate issue for that. https://github.com/StanfordBDHG/ENGAGE-HF-Firebase/issues/147

**Pull request merged**
